name: 'Build SAM GitHub Actions'
branding:
  icon: 'terminal'
  color: 'orange'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Golang
      uses: actions/setup-go@v3
      with:
        go-version: '^1.18'

    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Setup AWS CLI
      run: pip install awscli
      shell: bash

    - name: Setup AWS SAM CLI
      run: pip install aws-sam-cli
      shell: bash

    - name: Build AWS SAM
      run: |
        sam build -b dist && \
        if [ -e samconfig.toml ];then cp samconfig.toml dist/samconfig.toml; fi
      shell: bash

    - name: Compress Artifact
      run: |
        tar -czvf dist.tar.gz ./dist
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist.tar.gz
